In [7]:
import numpy as  np
import pandas as pd
from pandas import Series, DataFrame

In [8]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['ohio', 'colorado', 'utah', 'new york'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [9]:
data.loc['colorado', ['two', 'three']]

two      5
three    6
Name: colorado, dtype: int32

In [10]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: utah, dtype: int32

In [11]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: utah, dtype: int32

In [12]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
colorado     7    4    5
utah        11    8    9

In [14]:
data.loc[:'utah', 'two']

ohio        1
colorado    5
utah        9
Name: two, dtype: int32

In [16]:
data.iloc[:, :3][data.three > 5]

one  two  three
colorado    4    5      6
utah        8    9     10
new york   12   13     14

In [17]:
ser =pd.Series(np.arange(3.))

In [18]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [19]:
ser[-1]

KeyError: -1

In [20]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [21]:
ser[:1]

0    0.0
dtype: float64

In [22]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [23]:
ser.iloc[:1]

0    0.0
dtype: float64

In [24]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [25]:
s1 , s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64,
 a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [26]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [27]:
df1 = pd.DataFrame(np.arange(9).reshape((3, 3)), columns=list('bcd'),
                   index=['ohio', 'texas', 'colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['utha', 'ohio', 'texas', 'oregon'])

In [28]:
df1, df2

(          b  c  d
 ohio      0  1  2
 texas     3  4  5
 colorado  6  7  8,
           b     d     e
 utha    0.0   1.0   2.0
 ohio    3.0   4.0   5.0
 texas   6.0   7.0   8.0
 oregon  9.0  10.0  11.0)

In [29]:
df1 + df2

b   c     d   e
colorado  NaN NaN   NaN NaN
ohio      3.0 NaN   6.0 NaN
oregon    NaN NaN   NaN NaN
texas     9.0 NaN  12.0 NaN
utha      NaN NaN   NaN NaN

In [30]:
df1

b  c  d
ohio      0  1  2
texas     3  4  5
colorado  6  7  8

In [31]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [32]:
df1

A
0  1
1  2

In [33]:
df2

B
0  3
1  4

In [34]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [35]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [36]:
df2.loc[1, 'b'] = np.nan

In [37]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [38]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [39]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [40]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [41]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [42]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [44]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [45]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [46]:
arr[0]

array([0., 1., 2., 3.])

In [47]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [48]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['utha', 'ohio', 'texas', 'oregon'])

In [49]:
series = frame.iloc[0]

In [50]:
frame

b     d     e
utha    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [51]:
series

b    0.0
d    1.0
e    2.0
Name: utha, dtype: float64

In [52]:
frame - series

b    d    e
utha    0.0  0.0  0.0
ohio    3.0  3.0  3.0
texas   6.0  6.0  6.0
oregon  9.0  9.0  9.0

In [53]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [54]:
frame + series2

b   d     e   f
utha    0.0 NaN   3.0 NaN
ohio    3.0 NaN   6.0 NaN
texas   6.0 NaN   9.0 NaN
oregon  9.0 NaN  12.0 NaN

In [55]:
series3 = frame['d']

In [56]:
frame

b     d     e
utha    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [58]:
series3

utha       1.0
ohio       4.0
texas      7.0
oregon    10.0
Name: d, dtype: float64

In [59]:
frame.sub(series3, axis='index')

b    d    e
utha   -1.0  0.0  1.0
ohio   -1.0  0.0  1.0
texas  -1.0  0.0  1.0
oregon -1.0  0.0  1.0

In [60]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                   index=['utha', 'ohio', 'texas', 'oregon'])

In [61]:
frame

b         d         e
utha   -0.112161 -0.388078  0.342574
ohio    0.448526  1.881419  0.295779
texas   2.651853  0.959662  0.558414
oregon  0.059711  0.725456 -0.604615

In [62]:
np.abs(frame)

b         d         e
utha    0.112161  0.388078  0.342574
ohio    0.448526  1.881419  0.295779
texas   2.651853  0.959662  0.558414
oregon  0.059711  0.725456  0.604615

In [64]:
f = lambda x : x.max() - x.min()

In [65]:
frame.apply(f)

b    2.764014
d    2.269498
e    1.163029
dtype: float64

In [66]:
frame.apply(f, axis='columns')

utha      0.730653
ohio      1.585640
texas     2.093440
oregon    1.330071
dtype: float64

In [67]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [68]:
frame.apply(f)

b         d         e
min -0.112161 -0.388078 -0.604615
max  2.651853  1.881419  0.558414

In [ ]:
format = lambda x: '%.2f' % x