In [2]:
import numpy as np

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
arr2d[2]

array([7, 8, 9])

In [5]:
arr2d[0][2]

3

In [6]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [7]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
old_values = arr3d[0].copy()

In [11]:
arr3d[0] = 42

In [12]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3d[0] = old_values

In [14]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr3d [1, 0]

array([7, 8, 9])

In [16]:
x = arr3d[1]

In [17]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [18]:
arr = np.arange(10)

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [21]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [23]:
arr2d[1, :2]

array([4, 5])

In [24]:
arr2d[:2, 2]

array([3, 6])

In [25]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [26]:
arr2d[:2, 1:] = 0

In [27]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [49]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [50]:
data = np.random.randn(7,4)

In [51]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [52]:
data

array([[-0.09081483,  0.78861816,  0.10668023, -0.10107815],
       [-0.85958763,  0.58824283, -0.54885683, -1.36183066],
       [-0.06976599, -0.8312044 , -1.71404133,  0.7213311 ],
       [-0.38260286, -0.11852919,  0.06601704,  1.4448523 ],
       [-0.52101617,  0.32486147, -0.09833939,  1.26274005],
       [-0.43085794,  0.60830081, -0.34359317, -1.69719689],
       [ 0.50377896,  0.23436248,  1.27814446,  1.34302441]])

In [53]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [54]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [55]:
mask = (names == 'bob')|(names == 'will')

In [56]:
mask

array([ True, False,  True,  True,  True, False, False])

In [57]:
data[mask]

array([[-0.09081483,  0.78861816,  0.10668023, -0.10107815],
       [-0.06976599, -0.8312044 , -1.71404133,  0.7213311 ],
       [-0.38260286, -0.11852919,  0.06601704,  1.4448523 ],
       [-0.52101617,  0.32486147, -0.09833939,  1.26274005]])

In [59]:
data[names == 'bob']

array([[-0.09081483,  0.78861816,  0.10668023, -0.10107815],
       [-0.38260286, -0.11852919,  0.06601704,  1.4448523 ]])

In [60]:
data[names == 'bob', 2:]

array([[ 0.10668023, -0.10107815],
       [ 0.06601704,  1.4448523 ]])

In [61]:
data[names == 'bob', 3:]

array([[-0.10107815],
       [ 1.4448523 ]])

In [62]:
data[~(names == 'bob')]

array([[-0.85958763,  0.58824283, -0.54885683, -1.36183066],
       [-0.06976599, -0.8312044 , -1.71404133,  0.7213311 ],
       [-0.52101617,  0.32486147, -0.09833939,  1.26274005],
       [-0.43085794,  0.60830081, -0.34359317, -1.69719689],
       [ 0.50377896,  0.23436248,  1.27814446,  1.34302441]])

In [63]:
data[mask]

array([[-0.09081483,  0.78861816,  0.10668023, -0.10107815],
       [-0.06976599, -0.8312044 , -1.71404133,  0.7213311 ],
       [-0.38260286, -0.11852919,  0.06601704,  1.4448523 ],
       [-0.52101617,  0.32486147, -0.09833939,  1.26274005]])

In [64]:
cond = names == 'bob'

In [65]:
data[~cond]

array([[-0.85958763,  0.58824283, -0.54885683, -1.36183066],
       [-0.06976599, -0.8312044 , -1.71404133,  0.7213311 ],
       [-0.52101617,  0.32486147, -0.09833939,  1.26274005],
       [-0.43085794,  0.60830081, -0.34359317, -1.69719689],
       [ 0.50377896,  0.23436248,  1.27814446,  1.34302441]])

In [66]:
data[data < 0] = 0

In [67]:
data

array([[0.        , 0.78861816, 0.10668023, 0.        ],
       [0.        , 0.58824283, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.7213311 ],
       [0.        , 0.        , 0.06601704, 1.4448523 ],
       [0.        , 0.32486147, 0.        , 1.26274005],
       [0.        , 0.60830081, 0.        , 0.        ],
       [0.50377896, 0.23436248, 1.27814446, 1.34302441]])

In [68]:
data[names != 'joe'] = 7

In [69]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.58824283, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.60830081, 0.        , 0.        ],
       [0.50377896, 0.23436248, 1.27814446, 1.34302441]])

In [70]:
arr = np.empty((8, 4))

In [71]:
for i in range(8):
    arr[i] = i

In [72]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [73]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [74]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [75]:
arr = np.arange(32).reshape((8, 4))

In [76]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [77]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [78]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [79]:
arr = np.arange(15).reshape((3, 5))

In [80]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [82]:
arr = np.random.randn(6, 3)

In [83]:
arr

array([[ 0.81291494,  0.9222111 ,  0.27785879],
       [ 0.36542759,  0.50598385, -0.15088908],
       [ 0.49168542, -2.85628693,  1.22090278],
       [ 0.11251528,  1.02610092, -0.81567927],
       [ 1.61742178,  0.71922951, -0.15067313],
       [-0.76782671,  0.82536101, -0.27433771]])

In [84]:
np.dot(arr.T, arr)

array([[ 4.25439335,  0.17520026,  0.64620207],
       [ 0.17520026, 11.51626296, -4.47911708],
       [ 0.64620207, -4.47911708,  2.35387286]])

In [ ]:
arr = np.arange(16).resh