In [56]:
import numpy as np
import pandas as pd
import patsy

In [2]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [3]:
cat_s = s.astype('category')

In [4]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [5]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [6]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
actual_categories = ['a', 'b',  'c', 'd', 'e']

In [8]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [9]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [10]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [11]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [12]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [13]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [14]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [15]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [16]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [17]:
df = pd.DataFrame({'key':['a', 'b', 'c'] * 4, 'value':np.arange(12)})

In [18]:
df

key  value
0    a      0
1    b      1
2    c      2
3    a      3
4    b      4
5    c      5
6    a      6
7    b      7
8    c      8
9    a      9
10   b     10
11   c     11

In [19]:
g = df.groupby('key').value

In [20]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [21]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [22]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [23]:
g.transform(lambda x: x * 2)

0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
11    22
Name: value, dtype: int32

In [24]:
g.transform(lambda x: x.rank(ascending=False))

0     4
1     4
2     4
3     3
4     3
5     3
6     2
7     2
8     2
9     1
10    1
11    1
Name: value, dtype: int32

In [25]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [26]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [27]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [28]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [29]:
normalized = (df['value'] - g.transform('mean')) / g.transform('std')

In [30]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [31]:
N = 15
times = pd.date_range('2017-05-20 00:00', freq='1min', periods=N)
df = pd.DataFrame({'time': times, 'value': np.arange(N)})

In [32]:
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [33]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [34]:
df2 = pd.DataFrame({'time': times.repeat(3), 'key': np.tile(['a', 'b', 'c'], N), 'value': np.arange(N * 3.)})

In [35]:
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [36]:
df2

time key  value
0  2017-05-20 00:00:00   a    0.0
1  2017-05-20 00:00:00   b    1.0
2  2017-05-20 00:00:00   c    2.0
3  2017-05-20 00:01:00   a    3.0
4  2017-05-20 00:01:00   b    4.0
5  2017-05-20 00:01:00   c    5.0
6  2017-05-20 00:02:00   a    6.0
7  2017-05-20 00:02:00   b    7.0
8  2017-05-20 00:02:00   c    8.0
9  2017-05-20 00:03:00   a    9.0
10 2017-05-20 00:03:00   b   10.0
11 2017-05-20 00:03:00   c   11.0
12 2017-05-20 00:04:00   a   12.0
13 2017-05-20 00:04:00   b   13.0
14 2017-05-20 00:04:00   c   14.0
15 2017-05-20 00:05:00   a   15.0
16 2017-05-20 00:05:00   b   16.0
17 2017-05-20 00:05:00   c   17.0
18 2017-05-20 00:06:00   a   18.0
19 2017-05-20 00:06:00   b   19.0
20 2017-05-20 00:06:00   c   20.0
21 2017-05-20 00:07:00   a   21.0
22 2017-05-20 00:07:00   b   22.0
23 2017-05-20 00:07:00   c   23.0
24 2017-05-20 00:08:00   a   24.0
25 2017-05-20 00:08:00   b   25.0
26 2017-05-20 00:08:00   c   26.0
27 2017-05-20 00:09:00   a   27.0
28 2017-05-20 00:09:00   b   28.0
29 2017-05-20 00:09:00   c   29.0
30 2017-05-20 00:10:00   a   30.0
31 2017-05-20 00:10:00   b   31.0
32 2017-05-20 00:10:00   c   32.0
33 2017-05-20 00:11:00   a   33.0
34 2017-05-20 00:11:00   b   34.0
35 2017-05-20 00:11:00   c   35.0
36 2017-05-20 00:12:00   a   36.0
37 2017-05-20 00:12:00   b   37.0
38 2017-05-20 00:12:00   c   38.0
39 2017-05-20 00:13:00   a   39.0
40 2017-05-20 00:13:00   b   40.0
41 2017-05-20 00:13:00   c   41.0
42 2017-05-20 00:14:00   a   42.0
43 2017-05-20 00:14:00   b   43.0
44 2017-05-20 00:14:00   c   44.0

In [37]:
df2[:7]

time key  value
0 2017-05-20 00:00:00   a    0.0
1 2017-05-20 00:00:00   b    1.0
2 2017-05-20 00:00:00   c    2.0
3 2017-05-20 00:01:00   a    3.0
4 2017-05-20 00:01:00   b    4.0
5 2017-05-20 00:01:00   c    5.0
6 2017-05-20 00:02:00   a    6.0

In [38]:
data = pd.DataFrame({'x0':[1, 2, 3, 4, 5], 'x1':[0.01, -0.01, 0.25, -4.1, 0.], 'y':[-1.5, 0., 3.6, 1.3, -2.]})

In [39]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [40]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [41]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [42]:
df2 = pd.DataFrame(data.values, columns=['one', 'two', 'three'])

In [43]:
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [44]:
df3 = data.copy()

In [45]:
df3['strings']  = ['a', 'b', 'c', 'd', 'e']

In [46]:
df3

x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [47]:
df3.values

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [48]:
model_cols = ['xo', 'x1']

In [49]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'], categories=['a', 'b'])

In [50]:
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [51]:
dummies = pd.get_dummies(data.category, prefix='category')

In [52]:
data_with_dummies = data.drop('category', axis=1).join(dummies)

In [53]:
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5           1           0
1   2 -0.01  0.0           0           1
2   3  0.25  3.6           1           0
3   4 -4.10  1.3           1           0
4   5  0.00 -2.0           0           1

In [54]:
data = pd.DataFrame({'x0':[1, 2, 3, 4, 5], 'x1':[0.01, -0.01, 0.25, -4.1, 0.], 'y':[-1.5, 0., 3.6, 1.3, -2.]})

In [57]:
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [58]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [59]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [60]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [61]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [62]:
patsy.dmatrices('y ~ x0 + x1', data)[1]

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [64]:
coef, resid, _, _ = np.linalg.lstsq(X, y)

<ipython-input-64-ef4372856a50>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coef, resid, _, _ = np.linalg.lstsq(X, y)


In [65]:
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [66]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)

In [68]:
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [69]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)

In [70]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [71]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)

In [72]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [73]:
new_data = pd.DataFrame({'x0':[6, 7, 8, 9], 'x1':[3.1, -0.5, 0, 2.3], 'y':[1, 2, 3, 4]})

In [74]:
new_X = patsy.build_design_matrices([X.design_info], new_data)
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [75]:
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)

In [76]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [79]:
data = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
                     'key2':[0, 1, 0, 1, 0, 1, 0, 0],
                     'v1':[1, 2, 3, 4, 5, 6, 7, 8],
                     'v2':[-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]})

In [80]:
y, X = patsy.dmatrices('v2 ~ key1', data)
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [81]:
y, X = patsy.dmatrices('v2 ~ key1 + 0', data)

In [82]:
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [83]:
y, X = patsy.dmatrices('v2 ~ C(key2)', data)
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

In [84]:
data['key2'] = data['key2'].map({0: 'zero', 1:'one'})

In [85]:
data

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [86]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [ ]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)