In [4]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']

In [5]:
[x.upper() for x in strings if len(x) > 2 ]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [6]:
unique_lengths = {len(x) for x in strings}

In [7]:
unique_lengths

{1, 2, 3, 4, 6}

In [8]:
set(map(len, strings))

{1, 2, 3, 4, 6}

In [9]:
loc_mapping = {val : index for index, val in enumerate(strings)}

In [10]:
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [11]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [12]:
flattend = [x for tup in some_tuples for x in tup]

In [13]:
flattend

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
[[x for x in tup] for tup in some_tuples]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
path = '研究室情報'

In [16]:
f = open(path)

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [2]:
some_dict = {'a': 1, 'b': 2, 'c': 3}

In [3]:
for key in some_dict:
    print(key)

a
b
c


In [4]:
dict_iterator = iter(some_dict)

In [5]:
dict_iterator

In [6]:
list(dict_iterator)

['a', 'b', 'c']

In [10]:
def squares(n=10):
    print('Generating squares from 1 to {0}'.format(n **2 ))
    for i in range(1, n + 1):
        yield i ** 2

In [11]:
gen = squares()

In [12]:
gen

<generator object squares at 0x000001DC4E107200>

In [13]:
for x in gen:
    print(x, end=' ')

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [14]:
gen = (x ** 2 for x in range(100))

In [15]:
gen

<generator object <genexpr> at 0x000001DC4E1076D0>

In [16]:
sum(x ** 2 for x in range(100))

328350

In [17]:
dict((i, 1 ** 2) for i in range(5))

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1}

In [18]:
import itertools

In [20]:
first_letter = lambda x : x[0]

In [21]:
names = ['alan', 'adam', 'wes', 'will', 'albert', 'steven']

In [23]:
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names))

a ['alan', 'adam']
w ['wes', 'will']
a ['albert']
s ['steven']


In [25]:
import numpy as np

In [26]:
my_arr = np.arange(1000000)

In [30]:
my_list = list(range(1000000))

In [31]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 17.9 ms


In [32]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 775 ms


In [36]:
data = np.random.randn(3, 3)

In [37]:
data

array([[-0.16137585, -0.44308159,  0.44516002],
       [-0.84300839,  0.25323889,  0.18576484],
       [ 1.02733454,  0.80865575, -0.99916789]])

In [38]:
data * 100

array([[-16.13758529, -44.30815888,  44.51600218],
       [-84.30083883,  25.32388868,  18.57648376],
       [102.73345445,  80.86557501, -99.91678916]])

In [39]:
data + data

array([[-0.32275171, -0.88616318,  0.89032004],
       [-1.68601678,  0.50647777,  0.37152968],
       [ 2.05466909,  1.6173115 , -1.99833578]])

In [40]:
data.shape

(3, 3)

In [41]:
data.dtype

dtype('float64')

In [42]:
data1 =[6, 7.5, 8, 0, 1]

In [43]:
arr1 = np.array(data1)

In [44]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [45]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [46]:
arr2 = np.array(data2)

In [47]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
arr2.ndim

2

In [49]:
arr2.shape

(2, 4)

In [50]:
arr2.dtype

dtype('int32')

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [57]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])