In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [3]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [4]:
arr1.dtype

dtype('float64')

In [22]:
arrx = np.array([1, 2, 3, 4, 5])

In [23]:
float_arr = arr.astype(np.float64)

In [24]:
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7, -1.2, -2,6, 0.5])


In [26]:
arr.astype(np.int32)

array([ 3, -1, -2,  6,  0])

In [27]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [28]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [29]:
int_array = np.arange(10)

In [30]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [31]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
empty_uint32 = np.empty(8, dtype='u4')

In [33]:
empty_uint32 

array([  0,   1,   0, 468, 328,   0, 768,   0], dtype=uint32)

In [34]:
arr

array([ 3.7, -1.2, -2. ,  6. ,  0.5])

In [35]:
arr * arr

array([13.69,  1.44,  4.  , 36.  ,  0.25])

In [36]:
arr - arr

array([0., 0., 0., 0., 0.])

In [37]:
1 / arr

array([ 0.27027027, -0.83333333, -0.5       ,  0.16666667,  2.        ])

In [38]:
arrx > arr

array([False,  True,  True, False,  True])

In [45]:
arrg = np.arange(10)

In [46]:
arr

array([ 3.7, -1.2, -2. ,  6. ,  0.5])

In [47]:
arrg

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arrg[5]

5

In [50]:
arrg[5:8]

array([5, 6, 7])

In [51]:
arrg[5:8]  = 0

In [52]:
arrg

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

In [54]:
V = arrg[5:8]

In [55]:
V

array([0, 0, 0])

In [57]:
V[1] = 13

In [58]:
V

array([ 0, 13,  0])

In [59]:
arrg

array([ 0,  1,  2,  3,  4,  0, 13,  0,  8,  9])

In [60]:
V[:] = 7

In [61]:
arrg

array([0, 1, 2, 3, 4, 7, 7, 7, 8, 9])