In [1]:
import numpy as np

In [2]:
#SUM Σ
ans = 0
for i in range(1, 11):
    ans += 1
    print(ans)

1
2
3
4
5
6
7
8
9
10


In [3]:
N = 10
a = [i for i in range(1, N+1)]

ans = 0
for i in a:
    ans += 1
    print(ans)

1
2
3
4
5
6
7
8
9
10


In [4]:
#munti dimenstion SUM 
a = [[1, 2], [3, 4]]
ans = 0
for i in range(2):
    for j in range(2):
        ans += a[i][j]
    print(ans)

3
10


In [5]:
#all multiple PAI Π
a = [1, 2, 3]
ans = 1 #≠0
for i in a:
    ans *= i
    print(ans)

1
2
6


In [6]:
#munti dimenstion PAI
a = [[1, 2], [3, 4]]
ans = 1
for i in range(2):
    for j in range(2):
        ans *= a[i][j]
    print(ans)

2
24


In [7]:
#vector
a = np.array([25, 30, 10000])
b = np.array([40,90, 500])

ans1 = a + b
print(ans1)
ans2 = a - b
print(ans2)

[   65   120 10500]
[ -15  -60 9500]


In [8]:
#vector * scalor
c = 2
print(c * a)

ans3 = (1/c)*(ans1)
print(ans3)

[   50    60 20000]
[  32.5   60.  5250. ]


In [9]:
#adamarl product
ans4 = []
for i,j in zip(a, b):
    ans4.append(i*j)
    print(ans4)

[1000]
[1000, 2700]
[1000, 2700, 5000000]


In [10]:
#dot product
np.dot(a, b)

5003700

In [11]:
#closs product
np.outer(a, b)

array([[   1000,    2250,   12500],
       [   1200,    2700,   15000],
       [ 400000,  900000, 5000000]])

In [12]:
#bector's norm
np.linalg.norm(a, ord=2)

10000.076249709298

In [13]:
a = np.array([2, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])
axb = np.outer(a, b)
ans = np.dot(c, axb)
print(axb)

[[0 2 0]
 [0 0 0]
 [0 0 0]]


In [14]:
#matrix
A = np.array([[1, 2, 4], [2, 3, 4], [3, 6, 5]])
print(A)

[[1 2 4]
 [2 3 4]
 [3 6 5]]


In [15]:
A.T # transposed matrix

array([[1, 2, 3],
       [2, 3, 6],
       [4, 4, 5]])

In [16]:
E = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [17]:
B = np.array([[1, 5, 2], [5, 2, 7], [2, 6, 1]])

In [18]:
#matrix add multi
A + B

array([[ 2,  7,  6],
       [ 7,  5, 11],
       [ 5, 12,  6]])

In [19]:
A * B

array([[ 1, 10,  8],
       [10,  6, 28],
       [ 6, 36,  5]])

In [20]:
A * E

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [21]:
A + E

array([[2, 2, 4],
       [2, 4, 4],
       [3, 6, 6]])

In [22]:
a = np.array([[1], 
              [3], 
              [2]])

In [23]:
A * a

array([[ 1,  2,  4],
       [ 6,  9, 12],
       [ 6, 12, 10]])

In [24]:
#kronecker product
np.kron(A, B)

array([[ 1,  5,  2,  2, 10,  4,  4, 20,  8],
       [ 5,  2,  7, 10,  4, 14, 20,  8, 28],
       [ 2,  6,  1,  4, 12,  2,  8, 24,  4],
       [ 2, 10,  4,  3, 15,  6,  4, 20,  8],
       [10,  4, 14, 15,  6, 21, 20,  8, 28],
       [ 4, 12,  2,  6, 18,  3,  8, 24,  4],
       [ 3, 15,  6,  6, 30, 12,  5, 25, 10],
       [15,  6, 21, 30, 12, 42, 25, 10, 35],
       [ 6, 18,  3, 12, 36,  6, 10, 30,  5]])

In [25]:
#determinant
np.linalg.det(A)

6.999999999999999

In [26]:
np.linalg.det(B)

56.99999999999996

In [27]:
np.linalg.det(E)

1.0

In [28]:
#sign sgn(σ)
import itertools

def S(n):
    a = [i for i in range(1, n+1)]
    S = list(itertools.permutations(a))
    return S

def sgn(li):
    cnt = 0
    for i in range(len(li)): #bubble sort
        for j in range(len(li)-1-i):
            if li[j] > li[j+1]:
                li[j], li[j+1] = li[j+1], li[j]
                cnt += 1
    ans = 1 if cnt%2==0 else -1 #jadgment odd or even
    return ans,cnt

S = S(3) #3D symmetric group
for s in S:
    print(s,sgn(list(s)))

(1, 2, 3) (1, 0)
(1, 3, 2) (-1, 1)
(2, 1, 3) (-1, 1)
(2, 3, 1) (1, 2)
(3, 1, 2) (1, 2)
(3, 2, 1) (-1, 3)


In [29]:
#inverse matrix
Ai = np.linalg.inv(A)
print(Ai)
print(np.dot(A,Ai)) #A*Ai=E
print(np.dot(Ai,A)) #Ai*A=E

[[-1.28571429e+00  2.00000000e+00 -5.71428571e-01]
 [ 2.85714286e-01 -1.00000000e+00  5.71428571e-01]
 [ 4.28571429e-01  4.75809868e-17 -1.42857143e-01]]
[[ 1.00000000e+00  1.90323947e-16  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [-5.55111512e-17  2.37904934e-16  1.00000000e+00]]
[[ 1.00000000e+00  1.11022302e-15  9.99200722e-16]
 [-1.11022302e-16  1.00000000e+00 -1.11022302e-16]
 [ 2.77555756e-17 -5.55111512e-17  1.00000000e+00]]


In [30]:
#trace matrix
print(np.trace(A))
print(np.trace(B))
print(np.trace(E))

9
4
3
